version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bain_mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports: 
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  flask:
    build: .
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=db
      - DB_PORT=3306
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - app-network
    ports:
    - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "3000:80"

volumes:
  bain_mysql_data:

networks:
  app-network:
