services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bain_mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports: 
      - "3306:3306"

  flask:
    build:
      context: .
    image: ddhruvgupta/distance-flask:deploy
    environment:
      FLASK_ENV: development
      FLASK_APP: app:create_app
      DB_ROOT_PASSWORD: rootdev
      DB_NAME: dev_db
      DB_USER: dev_user
      DB_PASSWORD: devpass
      DATABASE_URL: mysql+pymysql://dev_user:devpass@db:3306/dev_db
      SQLALCHEMY_POOL_SIZE: 10
      SQLALCHEMY_MAX_OVERFLOW: 20
      SQLALCHEMY_POOL_TIMEOUT: 30
      SQLALCHEMY_POOL_RECYCLE: 1800
      SQLALCHEMY_POOL_PRE_PING: True
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ddhruvgupta/distance-frontend:deploy
    networks:
      - app-network
    ports:
      - "3000:80"
volumes:
  bain_mysql_data:

networks:
  app-network:
