"""inital

Revision ID: e2213319c554
Revises: 
Create Date: 2025-04-12 17:18:01.881162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2213319c554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distance_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distance_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distance_queries_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distance_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distance_queries_id'))

    op.drop_table('distance_queries')
    # ### end Alembic commands ###
